CREATE TABLE IF NOT EXISTS mvp_user (
  user_id BIGINT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mvp_market (
  market VARCHAR(32) PRIMARY KEY,
  base_asset VARCHAR(16) NOT NULL,
  quote_asset VARCHAR(16) NOT NULL,
  amount_precision INT NOT NULL,
  price_precision INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mvp_balance (
  user_id BIGINT NOT NULL,
  asset VARCHAR(16) NOT NULL,
  available DECIMAL(32,16) NOT NULL DEFAULT 0,
  frozen DECIMAL(32,16) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, asset)
);
